---
sidebar: sidebar 
permalink: scpivs44_minimum_ontap_privileges_required.html 
keywords:  
summary: Les privilèges minimum ONTAP requis varient en fonction des plug-ins SnapCenter utilisés pour la protection des données. 
---
= Privilèges ONTAP requis
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les privilèges minimum ONTAP requis varient en fonction des plug-ins SnapCenter utilisés pour la protection des données.



== Privilèges minimum ONTAP requis

Tous les plug-ins SnapCenter requièrent les privilèges minimaux suivants :

|===
| Commandes All-Access : privilèges minimum requis pour ONTAP 8.3 et versions ultérieures 


| event generate-autosupport-log 


| l'historique des tâches s'affiche
fin de la tâche 


| lun
la création de lun
suppression de la lun
lun igroup add
créez un groupe initiateur lun
suppression du groupe initiateur lun
renommer la lun igroup
affichage de la lun igroup
lun mapping des nœuds supplémentaires
création d'un mappage de lun
suppression du mappage de lun
mappage de lun supprimer-rapports-nœuds
les mappages de lun s'affichent
modification de lun
déplacement des lun dans le volume
lun hors ligne
lun en ligne
suppression de la réservation persistante de lun
redimensionner la lun
série de lun
affichage de la lun 


| destinations des listes snapmirror
ajout de règle snapmirror
règle de modification de snapmirror
règle de suppression de snapmirror
affichage des règles snapmirror
restauration snapmirror
montrer snapmirror
historique des données du mode snapmirror
mise à jour snapmirror
snapmirror update-ls-set 


| Version 


| création de clones de volumes
clone de volume affiche
démarrage du fractionnement du clone de volume
arrêt du fractionnement du clone de volume
création de volumes
destruction des volumes
création d'un clone de fichiers de volumes
volume fichier show-disk-usage
volume hors ligne
volume en ligne
modification de volume
création de qtree volume
suppression qtree du volume
modification de qtree volume
volume qtree show
restrictions de volume
volume affiché
création de copies snapshot de volume
suppression du snapshot de volume
modification de snapshot de volume
renommage snapshot de volume
restauration snapshot du volume
fichier de restauration de snapshot de volume
snapshot de volume apparaît
démontage de volume 


| cifs vserver
création d'un partage cifs vserver
suppression du partage cifs vserver
vserver cifs shadowcopy show
vserver cifs share show
cifs montrer un vserver
vserver export-policy
vserver export-policy créé
vserver export-policy delete
vserver export-policy create
vserver export-policy règle show
vserver export-policy show
iscsi vserver
vserver iscsi connection show
vserver show
interface réseau
failover-groups d'interface réseau
interface réseau affiche 
|===
|===
| Commandes en lecture seule : privilèges minimum requis pour ONTAP 8.3 et versions ultérieures 


| un vserver
homologue vserver 
|===

NOTE: Vous pouvez ignorer les messages d'avertissement concernant les commandes vserver non prises en charge.



== Autres informations sur ONTAP

* Si vous exécutez ONTAP 8.2.x :
+
Vous devez vous connecter en tant que `vsadmin` Sur la machine virtuelle de stockage pour disposer des privilèges appropriés pour les opérations du plug-in SnapCenter pour VMware vSphere.

* Si vous exécutez ONTAP 8.3 et versions ultérieures :
+
Vous devez vous connecter en tant que `vsadmin` ou avec un rôle dont les privilèges sont minimum indiqués dans les tableaux ci-dessus.

* Vous devez être l'administrateur du cluster pour créer et gérer les rôles utilisateur. Vous pouvez associer les utilisateurs à la machine virtuelle de stockage du cluster ou à la machine virtuelle de stockage.

