---
sidebar: sidebar 
permalink: scpivs44_minimum_vcenter_privileges_required.html 
keywords:  
summary: Avant de commencer le déploiement du plug-in SnapCenter pour VMware vSphere, assurez-vous de disposer du minimum de privilèges vCenter requis. 
---
= Privilèges vCenter minimum requis
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Avant de commencer le déploiement du plug-in SnapCenter pour VMware vSphere, assurez-vous de disposer du minimum de privilèges vCenter requis.



== Privilèges requis pour le rôle d'administrateur vCenter

Datastore.AllocateSpace
Datastore.Parcourir
Datastore.Supprimer
Gestion des fichiers et des data stores
Datastore.déplacer
Datastore.Renommer
Extension.Enregistrer
Extension.désenregistrer
Extension.mise à jour
Host.Config.AdvancedConfig
Host.Config.Resources
Host.Config.Settings
Host.Config.stockage
Host.local.CreateVM
Host.local.DeleteVM
Host.local.Rereconfig VM
Réseau.affecter
Resource.ApplyRecommendation
Resource.AssignVMToPool
Ressource.ColdMigrate
Ressource.HotMigrate
Resource.QueryVMotion
System.Anonyme
Système.lecture
System.View
Tâche.Créer
Tâche.mettre à jour
Virtualmachine.Config.AddExistingDisk
Virtualmachine.Config.AddNewDisk
Virtualmachine.Config.AdvancedConfig
Virtualmachine.Config.ReloadFromPath
Virtualmachine.Config.RemoveDisk
Virtualmachine.Config.Resource
Virtualmachine.GuestOperations.Execute
Virtualmachine.GuestOperations.Modifier
Virtualmachine.GuestOperations.Query
Virtualmachine.Interact.poweroff
Virtualmachine.Interact.PowerOn
Virtualmachine.Inventory.Créer
Virtualmachine.Inventory.CreateFromExisting
Virtualmachine.Inventory.Supprimer
Virtualmachine.Inventory.Move
Virtualmachine.Inventory.Register
Virtualmachine.Inventory.désenregistrer
Virtualmachine.State.CreateSnapshot
Virtualmachine.State.RemoveSnapshot
Virtualmachine.State.RevertToSnapshot



== Privilèges requis spécifiques au plug-in SnapCenter pour VMware vCenter

|===


| *Privilèges* | *Étiquette* 


| Fichier de restauration.netappSCV.Guest | Restauration de fichiers invités 


| Montage du distributeur auxiliaire à récupération.netappDist | Monter/démonter 


| NetappSCV.Backup.DeleteBackupJob | Supprimer le groupe de ressources/sauvegarde 


| NetappSCV.Configure.ConfigenceStorageSystems.Delete | Supprimer les systèmes de stockage 


| Vue du distributeur sélectif de NetApp | Afficher 


| NetappSCV.Recovery.Recovery VM | Restaurer la machine virtuelle 


| NetappSCV.Configure.ConfigureStorageSystems.AddUpdate | Ajouter/Modifier des systèmes de stockage 


| NetappSCV.Backup.BackupNow | Sauvegarder maintenant 


| NetappSCV.invité.configurer | Configuration invité 


| NetappSCV.Configure.ConfigtureSnapCenterServer | Configurez SnapCenter Server 


| Programmée pour le distributeur sélectif de NetApp. Sauvegarde | Créer un groupe de ressources 
|===